name: Hola Mundo
on: 
  push:
    branches: ["main"]

jobs:
  hola_mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "Hola DonWeb"
      - name: Fecha y hora
        run: date
      - name: Usuario actual
        run: whoami
      - name: Mostrar directorio actual
        run: pwd
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Mostrar contenido del directorio
        run: ls -la
      - name: Mostrar variables de entorno
        run: env
        
