name: Main

on:
  push:
    branches: ["main"]

jobs:
  call-build:
    uses: ./.github/workflows/build.yml
  call-test:
    needs: call-build
    uses: ./.github/workflows/test.yml
  call-deploy:
    needs: call-test
    uses: ./.github/workflows/deploy.yml
